### ISSUE TITLE
Is it working yet?

### ISSUE THREAD

**Issue by AnasR7** [yooouuri/bulma-vue#1]
when I just want to install with yarn this plugin package is not found.

**Comment by yooouuri** [comment]
Hey @AnasR7

This buefy/bulma Vue 3 port is a WIP. When I started this project, the bulma-vue package was taken on npm.

https://www.npmjs.com/package/bulma-vue

Now I see its free for registration, so I will do that.

In the meantime, I will upload a dist folder to the git and you can add this package a git url, see 5 in https://classic.yarnpkg.com/lang/en/docs/cli/add/#toc-adding-dependencies

Im going to work again on this in my spare time, because im going to use this for my (private) projects!

**Comment by KaKi87** [comment]
Hello,
Any progress ?
Thanks
